config/routes.rb
Rails.application.routes.draw do

  get 'employees/index'
  get 'employees/employee_projects'
  post 'employees/employee_projects'

  devise_for :users
  get 'home/index'
  get 'home/employee_projects'
  get 'home/dash_board'

  get 'controller/action'

  resources :employees
  resources :employee_categories
  resources :employee_positions
  resources :organizations
  resources :clients
  resources :projects
  resources :employee_logs do
    collection do
      get :calendar_view
    end
  end

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index'
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :employee_position
  belongs_to :employee_category
  belongs_to :organization
  belongs_to :user

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP },
            presence: true,
            uniqueness: true
  validates :mobile,:presence => true,
            :numericality => true,
            :length => { :minimum => 10, :maximum => 15 }
  validates :employee_no , presence: true , uniqueness: {scope: :organization_id}
  validates :first_name , presence: true
  validates :organization_id , presence: true

  after_create :create_user
  has_many :projects,:foreign_key => 'manager_id'
  has_many :employee_projects,:foreign_key => 'employee_id'

  def full_name
    self.first_name + " " + self.last_name
  end

  def create_user
    user = User.create(name: self.employee_no, role_id: 2, email: self.email, password: "pass"+self.employee_no)
    self.update_attributes(user_id: user.id)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_filter :authenticate_user!
  layout 'application'

  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
    @positions = EmployeePosition.all.map{|l| [l.name,l.id]}
    @categories = EmployeeCategory.all.map{|l| [l.name,l.id]}
    @organization = Organization.first
  end

  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_path, notice: "Employee #{@employee.employee_no} was successfully created." }
      else
        @positions = EmployeePosition.all.map{|l| [l.name,l.id]}
        @categories = EmployeeCategory.all.map{|l| [l.name,l.id]}
        @organization = Organization.first
        format.html { render :new }
      end
    end
  end

  def edit
    @employee = Employee.find params[:id]
    @positions = EmployeePosition.all.map{|l| [l.name,l.id]}
    @categories = EmployeeCategory.all.map{|l| [l.name,l.id]}
    @organization = Organization.first
  end

  def update
    @employee = Employee.find params[:id]
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employees_path, notice: 'Employee was successfully updated.' }
      else
        @positions = EmployeePosition.all.map{|l| [l.name,l.id]}
        @categories = EmployeeCategory.all.map{|l| [l.name,l.id]}
        @organization = Organization.first
        format.html { render :edit }
      end
    end

  end

  def destroy
    @employee = Employee.find params[:id]
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_path, notice: 'Employee was successfully destroyed.' }
    end
  end
  def employee_projects
    @project = Project.find(params[:project_id])
    @employees = Employee.where("id NOT IN(?)", @project.manager_id).map{|l| [l.full_name,l.id]}
    @project_employees = @project.employee_projects
    @employee_project = EmployeeProject.new
    if params[:employee_project]
      @employee_project = EmployeeProject.new(employee_project_params)
      if @employee_project.save
        redirect_to employees_employee_projects_path(:project_id=>params[:project_id]), notice: 'Employee was successfully updated.'
      end
    end

  end
  private
  def employee_params
    params.require(:employee).permit!
  end
  def employee_project_params
    params.require(:employee_project).permit!
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<main class="form">
  <div class="row">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-body">
            <%=form_for(@employee) do |emp|%>
                <% if @employee.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this project from being saved:</h2>

                      <ul>
                        <% @employee.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                      </ul>
                    </div>
                <% end %>

                <%= emp.hidden_field :organization_id, :value => @organization.id %>
                <div class="form-group row">
                  <label for="employee_no" class="col-md-4 col-form-label text-md-right">Employee No:</label>
                  <div class="col-md-6">
                    <%= emp.text_field :employee_no, autofocus: true, class: "form-control"  %>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="first_name" class="col-md-4 col-form-label text-md-right">First Name:</label>
                  <div class="col-md-6">
                    <%= emp.text_field :first_name, class: "form-control"  %>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="last_name" class="col-md-4 col-form-label text-md-right">Last Name:</label>
                  <div class="col-md-6">
                    <%= emp.text_field :last_name, class: "form-control"  %>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="joined_date" class="col-md-4 col-form-label text-md-right">Joined Date:</label>
                  <div class="col-md-6">
                    <%= emp.date_select :joined_date,:start_year => 2000,class: "form-control"  %>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="email" class="col-md-4 col-form-label text-md-right">Email ID:</label>
                  <div class="col-md-6">
                    <%= emp.email_field :email,class: "form-control"  %>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="mobile" class="col-md-4 col-form-label text-md-right">Mobile No:</label>
                  <div class="col-md-6">
                    <%= emp.text_field :mobile,class: "form-control"  %>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="employee_category" class="col-md-4 col-form-label text-md-right">Category:</label>
                  <div class="col-md-6">
                    <%= emp.select :employee_category_id, @categories,{prompt: 'Select'},{class: "form-control mdb-select"} %>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="employee_position" class="col-md-4 col-form-label text-md-right">Position:</label>
                  <div class="col-md-6">
                    <%= emp.select :employee_position_id, @positions,{prompt: 'Select'},{class: "form-control mdb-select"} %>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="location" class="col-md-4 col-form-label text-md-right">Status</label>
                  <div class="col-md-6">
                    <%= emp.check_box :status%>
                  </div>
                </div>

                <div class="form-group row">
                  <div class="col-md-6 text-center">
                    <%= emp.submit class: 'btn btn-primary' %>
                  </div>
                </div>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>

</main>

app/views/employees/edit.erb
<h4>Editing Employee</h4>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/edit_category.erb
<main class="form">
  <div class="row">
    <div class="row justify-content-center">
      <div class="col-md-9">
        <div class="card">
          <h4 class="form-heading">Employee Categories</h4>
          <hr class="style2">
          <div class="card-body">
            <%=form_for(:employee_category, :action=>emp_update_cat_url) do |cat|%>
                <% @employee_category.errors.full_messages.each do |msg| %>
                    <span class="help-block"><%= msg %></span>
                <% end %>
                <div class="form-group row">
                  <label for="name" class="col-md-4 col-form-label text-md-right">Category Name:</label>
                  <div class="col-md-6">
                    <%= cat.text_field :name, autofocus: true, autocomplete: "name", class: "form-control"  %>
                  </div>
                </div>
                <div class="form-group row">
                  <label for="location" class="col-md-4 col-form-label text-md-right">Status</label>
                  <div class="col-md-6">
                    <%= cat.check_box :status%>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-md-6 text-center">
                    <%= cat.submit "Add" ,class: 'btn btn-primary' %>
                  </div>
                </div>
            <%end%>
          </div>
        </div>
      </div>
    </div>
      </div>
    </main>

app/views/employees/edit_position.erb
<main class="form">
  <div class="row">
    <div class="row justify-content-center">
      <div class="col-md-9">
        <div class="card">
          <h4 class="form-heading">Employee Positions</h4>
          <hr class="style2">
          <div class="card-body">
            <%=form_for(:employee_position, :action=>emp_update_position_url) do |position|%>
                <% @employee_position.errors.full_messages.each do |msg| %>
                    <span class="help-block"><%= msg %></span>
                <% end %>
                <div class="form-group row">
                  <label for="name" class="col-md-4 col-form-label text-md-right">Position Name:</label>
                  <div class="col-md-6">
                    <%= position.text_field :name, autofocus: true, autocomplete: "name", class: "form-control"  %>
                  </div>
                </div>
                <div class="form-group row">
                  <label for="location" class="col-md-4 col-form-label text-md-right">Status</label>
                  <div class="col-md-6">
                    <%= position.check_box :status%>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-md-6 text-center">
                    <%= position.submit "Add" ,class: 'btn btn-primary' %>
                  </div>
                </div>
            <%end%>
          </div>
        </div>
      </div>
    </div>
      </div>
    </main>

app/views/employees/employee_projects.erb
<table class="table table-bordered table-responsive-md table-striped text-center">
  <thead>
  <tr>
    <th class="text-center">Project name</th>
    <th class="text-center">Client</th>
    <th class="text-center">Start date</th>
    <th class="text-center">End date</th>
    <th class="text-center">Manager</th>
    <th class="text-center">Status</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= @project.project_name %></td>
    <td><%= @project.client.client_name %></td>
    <td><%= @project.start_date %></td>
    <td><%= @project.end_date %></td>
    <td><%= @project.manager.full_name rescue nil %></td>
    <td><%= @project.status ? 'Active' : 'In-Active' %></td>
  </tr>
  <tr>
    <th class="text-left" colspan="6">Emp Name</th>
  </tr>
  <%@project_employees.each_with_index do |project, index | %>
      <tr>
        <td><%= index+ 1 %></td>
        <td colspan="5"><%= project.employee.full_name %></td>
      </tr>
  <%end%>
  </tbody>
</table>
<main class="form">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <%= form_for @employee_project, url: {action: "employee_projects", params: {project_id: @project.id}} do |f| %>
              <% if @employee_project.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@employee_project.errors.count, "error") %> prohibited this project from being saved:</h2>
                    <ul>
                      <% @employee_project.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
              <% end %>
              <div class="form-group row">
                <label for="location" class="col-md-4 col-form-label text-md-right">Employees</label>
                <div class="col-md-6">
                  <%= f.select :employee_id, @employees,{prompt: 'Select'},{class: "form-control mdb-select"} %>
                  <%= f.hidden_field :project_id ,value: @project.id%>
                </div>
              </div>


              <div class="form-group row">
                <div class="col-md-6 text-center">
                  <%= f.submit class: 'btn btn-primary' %>
                </div>
              </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/employees/index.html.erb
<div class="span4" >
  <h4 class="form-heading">Employees</h4>
  <%unless @employees.blank?%>
      <table class="table table-bordered table-responsive-md table-striped text-center">
        <thead>
        <tr>
          <th class="text-center">Employee No.</th>
          <th class="text-center">Name</th>
          <th class="text-center">Organization</th>
        </tr>
        </thead>
        <tbody>
        <%@employees.each do |employee|%>
            <tr>
              <td class="pt-3-half" contenteditable="true"><%= employee.employee_no %></td>
              <td class="pt-3-half" contenteditable="true"><%= employee.full_name rescue nil%></td>
              <td class="pt-3-half" contenteditable="true"><%= employee.organization.name rescue "" %></td>
              <td class="pt-3-half">
                <%= link_to 'Edit', edit_employee_path(employee)%> |
                <%= link_to 'Delete', employee_path(employee),method: :delete,data: { confirm: 'Are You sure?' }%>
              </td>
            </tr>
        <%end%>
        </tbody>
      </table>
  <%end%>
  <%= link_to 'Add Employees', new_employee_path  %>
</div>

app/views/employees/new.erb
<main class="form">
  <div class="row">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <h2 class="form-heading">Employees</h2>

          <div class="card-body">
            <%=form_for(@employee) do |emp|%>
                <% if @employee.errors.any? %>
                    <ul class="alert alert-danger">
                      <% @employee.errors.full_messages.each do |msg| %>
                          <li class="alert-danger"><%= msg %></li>
                      <% end %>
                    </ul>
                <% end %>

                <div class="form-group row">
                  <label for="employee_no" class="col-md-4 col-form-label text-md-right">Employee No:</label>
                  <div class="col-md-6">
                    <%= emp.text_field :employee_no, autofocus: true, class: "form-control"  %>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="first_name" class="col-md-4 col-form-label text-md-right">First Name:</label>
                  <div class="col-md-6">
                    <%= emp.text_field :first_name, class: "form-control"  %>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="last_name" class="col-md-4 col-form-label text-md-right">Last Name:</label>
                  <div class="col-md-6">
                    <%= emp.text_field :last_name, class: "form-control"  %>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="joined_date" class="col-md-4 col-form-label text-md-right">Joined Date:</label>
                  <div class="col-md-6">
                    <%= emp.date_select :joined_date,:start_year => 2000,class: "form-control"  %>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="email" class="col-md-4 col-form-label text-md-right">Email ID:</label>
                  <div class="col-md-6">
                    <%= emp.email_field :email,class: "form-control"  %>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="mobile" class="col-md-4 col-form-label text-md-right">Mobile No:</label>
                  <div class="col-md-6">
                    <%= emp.text_field :mobile,class: "form-control"  %>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="employee_category" class="col-md-4 col-form-label text-md-right">Category:</label>
                  <div class="col-md-6">
                    <%= emp.select :employee_category_id, @categories,{prompt: 'Select'},{class: "form-control mdb-select"} %>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="employee_position" class="col-md-4 col-form-label text-md-right">Position:</label>
                  <div class="col-md-6">
                    <%= emp.select :employee_position_id, @positions,{prompt: 'Select'},{class: "form-control mdb-select"} %>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="organization" class="col-md-4 col-form-label text-md-right">Organization:</label>
                  <div class="col-md-6">
                    <%= emp.select :organization_id, @organizations,{prompt: 'Select'},{class: "form-control mdb-select"} %>
                  </div>
                </div>

                <div class="form-group row">
                  <label for="location" class="col-md-4 col-form-label text-md-right">Status</label>
                  <div class="col-md-6">
                    <%= emp.check_box :status%>
                  </div>
                </div>

                <div class="form-group row">
                  <div class="col-md-6 text-center">
                    <%= emp.submit "Add" ,class: 'btn btn-primary' %>
                  </div>
                </div>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>

</main>

app/views/employees/new.html.erb
<h4>New Employee</h4>
<hr class="style2">
<%= render 'form' %>
<%= link_to 'Back', employees_path %>

app/views/employees/new_category.erb
<main class="form">
  <div class="row">
    <div class="row justify-content-center">
      <div class="col-md-9">
        <div class="card">
          <h4 class="form-heading">Employee Categories</h4>
          <hr class="style2">
          <div class="card-body">
            <%=form_for(:employee_category, :action=> employees_new_category_path ) do |cat|%>
                <% @employee_category.errors.full_messages.each do |msg| %>
                    <span class="alert alert-danger"><%= msg %></span>
                <% end %>
                <div class="form-group row">
                  <label for="name" class="col-md-4 col-form-label text-md-right">Category Name:</label>
                  <div class="col-md-6">
                    <%= cat.text_field :name, autofocus: true, autocomplete: "name", class: "form-control"  %>
                  </div>
                </div>
                <div class="form-group row">
                  <label for="location" class="col-md-4 col-form-label text-md-right">Status</label>
                  <div class="col-md-6">
                    <%= cat.check_box :status%>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-md-6 text-center">
                    <%= cat.submit "Add" ,class: 'btn btn-primary' %>
                  </div>
                </div>
            <%end%>
          </div>
        </div>
        <div class="row" >
          <%unless @employee_categories.blank?%>
              <table class="table table-bordered table-responsive-md table-striped text-center">
                <thead>
                <tr>
                  <th class="text-center">Category Name</th>
                  <th class="text-center">Status</th>
                  <th class="text-center"></th>
                </tr>
                </thead>
                <tbody>
                <%@employee_categories.each do |category|%>
                    <tr>
                      <td class="pt-3-half" contenteditable="true"><%= category.name%></td>
                      <td class="pt-3-half" contenteditable="true"><%= category.status? ? 'Active' : 'In-Active'%></td>
                      <td class="pt-3-half"><%= link_to 'Edit', emp_edit_cat_url(category)%></td>
                    </tr>
                <%end%>
                </tbody>
              </table>
          <%end%>
        </div>
      </div>
    </div>

  </div>

</main>

app/views/employees/new_position.erb
<main class="form">
  <div class="row">
    <div class="row justify-content-center">
      <div class="col-md-9">
        <div class="card">
          <h4 class="form-heading">Employee Positions</h4>
          <hr class="style2">
          <div class="card-body">

            <%=form_for(:employee_position, :action=>employees_new_position_path) do |position|%>
                <% @employee_position.errors.full_messages.each do |msg| %>

                    <span class="alert alert-danger" style="margin: 1em;"><%= msg %></span>
                <% end %>
                <div class="form-group row">
                  <label for="name" class="col-md-4 col-form-label text-md-right">Position Name:</label>
                  <div class="col-md-6">
                    <%= position.text_field :name, autofocus: true, autocomplete: "name", class: "form-control"  %>
                  </div>
                </div>
                <div class="form-group row">
                  <label for="location" class="col-md-4 col-form-label text-md-right">Status</label>
                  <div class="col-md-6">
                    <%= position.check_box :status%>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-md-6 text-center">
                    <%= position.submit "Add" ,class: 'btn btn-primary' %>
                  </div>
                </div>
            <%end%>
          </div>
        </div>
        <div class="row" >
          <%unless @employee_positions.blank?%>

              <table class="table table-bordered table-responsive-md table-striped text-center">
                <thead>
                <tr>
                  <th class="text-center">Position Name</th>
                  <th class="text-center">Status</th>
                  <th class="text-center"></th>
                </tr>
                </thead>
                <tbody>
                <%@employee_positions.each do |position|%>
                    <tr>
                      <td class="pt-3-half" contenteditable="true"><%= position.name%></td>
                      <td class="pt-3-half" contenteditable="true"><%= position.status? ? 'Active' : 'In-Active'%></td>
                      <td class="pt-3-half" >
                        <%= link_to "Edit", emp_edit_position_url(position),class: "edit" %>
                      </td>
                    </tr>
                <%end%>
                </tbody>
              </table>
          <%end%>
        </div>
      </div>
    </div>

  </div>

</main>

app/views/employees/show.html.erb
<table class="table table-bordered table-responsive-md table-striped text-center">
  <tr>
    <td><strong>Employee No:</strong></td>
    <td><%= @employee.employee_no %></td>
  </tr>

  <tr>
    <td><strong>First Name:</strong></td>
    <td><%= @employee.first_name %></td>
  </tr>

  <tr>
    <td><strong>Last Name:</strong></td>
    <td><%= @employee.last_name %></td>
  </tr>

  <tr>
    <td><strong>Joined Date:</strong></td>
    <td><%= @employee.joined_date %></td>
  </tr>

  <tr>
    <td><strong>Email ID:</strong></td>
    <td><%= @employee.email %></td>
  </tr>

  <tr>
    <td><strong>Mobile No:</strong></td>
    <td><%= @employee.mobile %></td>
  </tr>

  <tr>
    <td><strong>Category:</strong></td>
    <td><%= @employee.employee_category.name %></td>
  </tr>

  <tr>
    <td><strong>Position:</strong></td>
    <td><%= @employee.employee_position.name %></td>
  </tr>

</table>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %> |