config/routes.rb
Rails.application.routes.draw do

  get 'employees/index'
  get 'employees/employee_projects'
  post 'employees/employee_projects'

  devise_for :users
  get 'home/index'
  get 'home/employee_projects'
  get 'home/dash_board'

  get 'controller/action'

  resources :employees
  resources :employee_categories
  resources :employee_positions
  resources :organizations
  resources :clients
  resources :projects
  resources :employee_logs do
    collection do
      get :calendar_view
    end
  end

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index'
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :project_name,presence: true
  validates :client_id,presence: true

  belongs_to :client
  belongs_to :manager, class_name: 'Employee'
  has_many :employee_projects,:foreign_key => 'project_id'


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
    @clients = Client.all.map{|f| [f.client_name,f.id]}
    @managers = Employee.all.map{|e| [e.full_name,e.id]}
  end

  def edit
    @clients = Client.all.map{|f| [f.client_name,f.id]}
    @managers = Employee.all.map{|e| [e.full_name,e.id]}
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:project_name, :client_id, :start_date, :end_date, :manager_id, :status)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<main class="form">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <%= form_for(@project,:multipart => true) do |f| %>
              <% if @project.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

                    <ul>
                      <% @project.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
              <% end %>

              <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">Project</label>
                <div class="col-md-6">
                  <%= f.text_field :project_name,class: "form-control" %>
                </div>
              </div>

              <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">Client</label>
                <div class="col-md-6">
                  <%= f.select :client_id,@clients,{prompt: 'Select'},{class: "form-control mdb-select"} %>
                </div>
              </div>

              <div class="form-group row">
                <label for="location" class="col-md-4 col-form-label text-md-right">Start Date</label>
                <div class="col-md-6">
                  <%= f.date_select :start_date,class: "form-control" %>
                </div>
              </div>
              <div class="form-group row">
                <label for="website" class="col-md-4 col-form-label text-md-right">End Date</label>
                <div class="col-md-6">
                  <%= f.date_select :end_date,class: "form-control" %>
                </div>
              </div>

              <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">Manager</label>
                <div class="col-md-6">
                  <%= f.select :manager_id,@managers,{prompt: 'Select'},{class: "form-control mdb-select"} %>
                </div>
              </div>

              <div class="form-group row">
                <label for="location" class="col-md-4 col-form-label text-md-right">Status</label>
                <div class="col-md-6">
                  <%= f.check_box :status%>
                </div>
              </div>

              <div class="form-group row">
                <div class="col-md-6 text-center">
                  <%= f.submit class: 'btn btn-primary' %>
                </div>
              </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/projects/edit.html.erb
<h4>Editing Project</h4>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h4>Listing Projects</h4>

<table class="table table-bordered table-responsive-md table-striped text-center">
  <thead>
    <tr>
      <th class="text-center">Project name</th>
      <th class="text-center">Client</th>
      <th class="text-center">Start date</th>
      <th class="text-center">End date</th>
      <th class="text-center">Manager</th>
      <th class="text-center">Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.project_name %></td>
        <td><%= project.client.client_name rescue nil %></td>
        <td><%= project.start_date %></td>
        <td><%= project.end_date %></td>
        <td><%= project.manager.full_name rescue nil %></td>
        <td><%= project.status ? 'Active' : 'In-Active' %></td>
        <td><%= link_to 'Show', project, :class=>"btn btn-small btn-info" %></td>
        <td><%= link_to 'Edit', edit_project_path(project), :class=>"btn btn-small btn-info" %></td>
        <td>
          <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } , :class=>"btn btn-small btn-danger"%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path, :class=>"btn btn-small btn-primary" %>

app/views/projects/new.html.erb
<h4>New Project</h4>
<hr class="style2">
<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<table class="table table-bordered table-responsive-md table-striped text-center">
  <tr>
    <td><strong>Project name:</strong></td>
    <td><%= @project.project_name %></td>
  </tr>

  <tr>
    <td><strong>Client:</strong></td>
    <td><%= @project.client.client_name %></td>
  </tr>

  <tr>
    <td><strong>Start date:</strong></td>
    <td><%= @project.start_date %></td>
  </tr>

  <tr>
    <td><strong>End date:</strong></td>
    <td><%= @project.end_date %></td>
  </tr>

  <tr>
    <td><strong>Manager:</strong></td>
    <td><%= @project.manager.full_name %></td>
  </tr>

  <tr>
    <td><strong>Status:</strong></td>
    <td><%= @project.status ? 'Active' : 'In-Active' %></td>
  </tr>

</table>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>|
<%= link_to 'Enroll Emp', employees_employee_projects_path(:project_id=>@project.id) %>