config/routes.rb
Rails.application.routes.draw do

  get 'employees/index'
  get 'employees/employee_projects'
  post 'employees/employee_projects'

  devise_for :users
  get 'home/index'
  get 'home/employee_projects'
  get 'home/dash_board'

  get 'controller/action'

  resources :employees
  resources :employee_categories
  resources :employee_positions
  resources :organizations
  resources :clients
  resources :projects
  resources :employee_logs do
    collection do
      get :calendar_view
    end
  end

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index'
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  validates :name,uniqueness: true,presence: true
  belongs_to :location
  has_many :employees

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @organizations = Organization.all
  end


  def new
    @organization = Organization.new
    @locations = Location.all.map{|l| [l.name,l.id]} rescue []
  end

  def create
    @organization = Organization.new(organization_params)
    respond_to do |format|
      if @organization.save
        format.html { redirect_to organizations_path, notice: 'Organization was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @organization = Organization.find params[:id]
    @locations = Location.all.map{|l| [l.name,l.id]}
  end

  def update
    @organization = Organization.find params[:id]
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to organizations_path, notice: 'Organization was successfully updated.' }
      else
        @locations = Location.all.map{|l| [l.name,l.id]} rescue []
        format.html { render :edit }
      end
    end
  end

  def destroy
    @organization = Organization.find params[:id]
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_path, notice: 'Organization was successfully destroyed.' }
    end
  end

  private
  def organization_params
    params.require(:organization).permit(:name,:location_id,:website,:logo)
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organization/edit.erb
<main class="form">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <h2 class="form-heading">Organization</h2>
        <div class="card-body">
          <%= form_for(@organization, url: organization_edit_path,:multipart => true) do |f| %>
              <%= render "devise/shared/error_messages", resource: @organization %>

              <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>
                <div class="col-md-6">
                  <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control" %>
                </div>
              </div>
              <div class="form-group row">
                <label for="location" class="col-md-4 col-form-label text-md-right">Location</label>
                <div class="col-md-6">
                  <%= f.select :location, @locations,{prompt: 'Select'},{class: "form-control mdb-select"} %>
                </div>
              </div>
              <div class="form-group row">
                <label for="website" class="col-md-4 col-form-label text-md-right">Website</label>
                <div class="col-md-6">
                  <%= f.text_field :website, autocomplete: "website", class: "form-control" %>
                </div>
              </div>
              <div class="form-group row">
                <label for="logo" class="col-md-4 col-form-label text-md-right">Logo</label>
                <div class="col-md-6">
                  <%= f.file_field :logo, class: "form-control" %>
                </div>
              </div>
              <div class="actions">
                <%= f.submit "Add" ,class: 'btn btn-primary' %>
              </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
    </main>

app/views/organization/new.html.erb
<main class="form">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <h2 class="form-heading">Organization</h2>
          <div class="card-body">
            <%= form_for(@organization, url: organization_new_path,:multipart => true) do |f| %>
                <%= render "devise/shared/error_messages", resource: @organization %>

                <div class="form-group row">
                  <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>
                  <div class="col-md-6">
                    <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control" %>
                  </div>
                </div>
                <div class="form-group row">
                  <label for="location" class="col-md-4 col-form-label text-md-right">Location</label>
                  <div class="col-md-6">
                    <%= f.select :location, @locations,{prompt: 'Select'},{class: "form-control mdb-select"} %>
                  </div>
                </div>
                <div class="form-group row">
                  <label for="website" class="col-md-4 col-form-label text-md-right">Website</label>
                  <div class="col-md-6">
                    <%= f.text_field :website, autocomplete: "website", class: "form-control" %>
                  </div>
                </div>
                <div class="form-group row">
                  <label for="logo" class="col-md-4 col-form-label text-md-right">Logo</label>
                  <div class="col-md-6">
                    <%= f.file_field :logo, class: "form-control" %>
                  </div>
                </div>
                <div class="actions">
                  <%= f.submit "Add" ,class: 'btn btn-primary' %>
                </div>
            <%end%>
          </div>
        </div>
      </div>
    </div>

    <div class="span4" >
      <%unless @organizations.blank?%>
          <table class="table table-bordered table-responsive-md table-striped text-center">
            <thead>
            <tr>
              <th class="text-center">Name</th>
              <th class="text-center">Location</th>
              <th class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>
            <%@organizations.each do |organization|%>
                <tr>
                  <td class="pt-3-half" contenteditable="true"><%= link_to organization.name,organization.website ,:target => '_blank' %></td>
                  <td class="pt-3-half" contenteditable="true"><%= organization.location.name rescue "" %></td>
                  <td class="pt-3-half"><%= link_to 'Edit', edit_organization_path(organization)%></td>
                </tr>
            <%end%>
            </tbody>
          </table>
      <%end%>
    </div>

</main>