config/routes.rb
Rails.application.routes.draw do

  get 'employees/index'
  get 'employees/employee_projects'
  post 'employees/employee_projects'

  devise_for :users
  get 'home/index'
  get 'home/employee_projects'
  get 'home/dash_board'

  get 'controller/action'

  resources :employees
  resources :employee_categories
  resources :employee_positions
  resources :organizations
  resources :clients
  resources :projects
  resources :employee_logs do
    collection do
      get :calendar_view
    end
  end

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index'
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :organization

  validates :client_name,presence: true ,uniqueness: {scope: :organization_id}
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :employee_position
  belongs_to :employee_category
  belongs_to :organization
  belongs_to :user

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP },
            presence: true,
            uniqueness: true
  validates :mobile,:presence => true,
            :numericality => true,
            :length => { :minimum => 10, :maximum => 15 }
  validates :employee_no , presence: true , uniqueness: {scope: :organization_id}
  validates :first_name , presence: true
  validates :organization_id , presence: true

  after_create :create_user
  has_many :projects,:foreign_key => 'manager_id'
  has_many :employee_projects,:foreign_key => 'employee_id'

  def full_name
    self.first_name + " " + self.last_name
  end

  def create_user
    user = User.create(name: self.employee_no, role_id: 2, email: self.email, password: "pass"+self.employee_no)
    self.update_attributes(user_id: user.id)
  end
end

app/models/employee_category.rb
class EmployeeCategory < ActiveRecord::Base
  validates :name,uniqueness: true,presence: true

end

app/models/employee_log.rb
class EmployeeLog < ActiveRecord::Base
  belongs_to :employee
end

app/models/employee_position.rb
class EmployeePosition < ActiveRecord::Base
  validates :name,uniqueness: true,presence: true

end

app/models/employee_project.rb
class EmployeeProject < ActiveRecord::Base
  belongs_to :employee
  belongs_to :project
  validates :employee_id,presence: true ,uniqueness: {scope: :project_id}

end

app/models/location.rb
class Location < ActiveRecord::Base
  validates :name,uniqueness: true,presence: true
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  validates :name,uniqueness: true,presence: true
  belongs_to :location
  has_many :employees

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :project_name,presence: true
  validates :client_id,presence: true

  belongs_to :client
  belongs_to :manager, class_name: 'Employee'
  has_many :employee_projects,:foreign_key => 'project_id'


end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
  validates :name,uniqueness: true,presence: true #, :scope => :sports_org_id
end

app/models/user.rb
class User < ActiveRecord::Base

  belongs_to :roles
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable
  has_one :employee_entry,:class_name=>"Employee",:foreign_key=>"user_id"

  def admin(user)
    if user.role_id == 1
      role = true
    else
      role = false
    end
    return role
  end

  def employee_record
    self.employee_entry
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @clients = Client.all
  end

  def new
    @client = Client.new
    @organization = Organization.first
  end

  def create
    @client = Client.new(client_params)
    @organization = Organization.first

    respond_to do |format|
      if @client.save
        format.html { redirect_to clients_path, notice: 'Client was successfully created.' }
      else
        format.html { render :new }
      end
    end

  end

  def edit
    @client = Client.find params[:id]
    @organization = Organization.first
  end

  def update
    @client = Client.find params[:id]
    @organization = Organization.first

    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to clients_path, notice: 'Client was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @client = Client.find params[:id]
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_path, notice: 'Client was successfully destroyed.' }
    end
  end

  private
  def client_params
    params.require(:client).permit(:client_name,:organization_id ,:status)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   before_filter :authenticate_user!
   layout :determine_layout

   def determine_layout
     role = current_user.role_id.to_s
     return (role.eql?('1') ? "application" : "employee")
   end

   def index
     path = case current_user.role_id.to_s
              when '1'
                home_dash_board_path
              when '2'
                home_employee_projects_path
              else
                home_employee_projects_path
            end

     redirect_to path
   end

   def dash_board

   end
   def employee_projects
      @projects = current_user.employee.projects rescue []
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employee_logs_helper.rb
module EmployeeLogsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Project Tracking" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>
  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"><%= image_tag(Organization.first.logo, size: '25') rescue "Logo" %></a>
    <a class="navbar-brand" href="#"><%= Organization.first.name rescue "OrganizationName" %></a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
      </ul>
    </div>
  </div>
</div>
<br><br><br>
<div class="container">
  <div class="row">
    <%if current_user.admin(current_user)%>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h4>Employee Section</h4>
            <ul class="nav nav-list">
              <li class="nav-header"><%= link_to "Employee Categories",  employee_categories_path %></li>
              <li><%= link_to "Employee Positions",   employee_positions_path %></li>
              <li><%= link_to "Organization", organizations_path %></li>
              <li><%= link_to "Employees", employees_path  %></li>
              <li><%= link_to "Client", clients_path  %></li>
              <li><%= link_to "Projects", projects_path  %></li>
            </ul>

          </div><!--/.well -->
        </div><!--/span-->
    <%end%>
    <div class="col-lg-9">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div><!--/row-->
  <hr class="style2">
  <footer>
    <p>&copy; Company 2019</p>
  </footer>

</div> <!-- /container -->

</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ProjectTrack" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>


    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>



      </div><!--/row-->



    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/employee.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ProjectTrack" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><%= image_tag(Organization.first.logo, size: '25') rescue "Logo" %></a>
        <a class="navbar-brand" href="#"><%= Organization.first.name rescue "OrganizationName" %></a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to image_tag("calendar.png", :border=>0, :class => 'calendar_icon',:width => 25),{action: 'calendar_view',controller: 'employee_logs'} %></li>
            <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">

        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3><%= current_user.name rescue ''%></h3>
            <ul class="nav nav-list">
              <li><%= link_to "Client", home_employee_projects_path  %></li>
              <li><%= link_to "Employee Logs", employee_logs_path  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->


    </div> <!-- /container -->
    <hr class="style2">
    <footer>
      <p>&copy; Company 2019</p>
    </footer>
  </body>
</html>